
services:
  hotelhub.webapi:
    image: hotelhub.webapi
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: src/HotelHub.WebAPI/Dockerfile
#
#  postgres: # https://hub.docker.com/_/postgres
#    image: postgres:${POSTGRES_VERSION}
#    container_name: hotelhub_postgres
#    restart: on-failure # only restart if the container crashes, but not if it's stopped manually
#    environment:
#      POSTGRES_DB: hotelhub
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "5432:5432"
#    volumes:
#      - vol_hotelhub_postgres:/var/lib/postgresql/data
#    networks:
#      - hotelhub_network
#
#
#volumes:
#  vol_hotelhub_postgres:

networks:
  hotelhub_network:
    driver: bridge